// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn1Tuw9oKbCS3Zu46aL9fdjxdw2n1wFsc',
    appId: '1:950520508982:web:fa5f42fe69e546d3db1e97',
    messagingSenderId: '950520508982',
    projectId: 'thai-fabric-check-in-app',
    authDomain: 'thai-fabric-check-in-app.firebaseapp.com',
    storageBucket: 'thai-fabric-check-in-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtz-v8goEF1UVFEERV7eEi3yyiHMJ6Dm0',
    appId: '1:950520508982:android:b74796cf8d889ad5db1e97',
    messagingSenderId: '950520508982',
    projectId: 'thai-fabric-check-in-app',
    storageBucket: 'thai-fabric-check-in-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8-Mw3xq3h0VkNreN6RK-dUQSsD840Neg',
    appId: '1:950520508982:ios:1c9b54c5e302e9dadb1e97',
    messagingSenderId: '950520508982',
    projectId: 'thai-fabric-check-in-app',
    storageBucket: 'thai-fabric-check-in-app.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

}